title: LF Energy Foundation Artwork 
description: >-
  Logos and artwork for LF Energy Foundation and it's hosted projects

# Settings
primary_logo: other/lf-energy/horizontal/color/lf-energy-horizontal-color.svg
header_logo: other/lf-energy/horizontal/white/lf-energy-horizontal-white.svg
github_repo: https://github.com/lf-energy/artwork
header_image: assets/img/lfe_top_bg.png
theme_color_1: 3a56e9
theme_color_2: 008f65
favicon: assets/img/favicon.png
trademark_text: Use of any trademark or logo is subject to the trademark policy available at <a href="https://www.linuxfoundation.org/trademark-usage">https://www.linuxfoundation.org/trademark-usage</a> with the key excepts available at <a href="LICENSE.md">LICENSE.md</a>. Questions? Please email <a href="mailto:info@lfenergy.org">info@lfenergy.org</a>. 
logo_categories: 
  - Projects
  - Working Groups
  - SIGs
  - Other Logos
ga_tracking_id: 361402579

readme_index:
  with_frontmatter: true
plugins:
  - jekyll-remote-theme
remote_theme: jmertic/artwork-template
